
name: ESP32

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

on:
  push:
  pull_request:
    paths-ignore:
      - "examples/**"
      - "README.md"
      - "ci/*unix*.sh"
      - ".github/workflows/build_*.yml"
      

jobs:
  tensorflow_micropython_esp32_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with psram support and 16MB Flash firmware
        run: |
          cd ..
          echo "BUILDING MICROLITE_SPIRAM_16M"
          source ./scripts/build.sh && build_esp32 "MICROLITE_SPIRAM_16M"
          TARGET=$(pwd)/dependencies/micropython/ports/esp32
          echo "TARGET=$TARGET"
          ./scripts/assemble-unified-image-esp.sh $TARGET "MICROLITE_SPIRAM_16M"
          ls $TARGET/build-MICROLITE_SPIRAM_16M
        shell: bash

      - name: Archive ESP32-MICROLITE_SPIRAM_16M firmware
        uses: actions/upload-artifact@v4
        with:
          name: microlite-esp32-spiram-16m-firmware
          path: /home/runner/work/tensorflow-micropython-examples/dependencies/micropython/ports/esp32/build-MICROLITE_SPIRAM_16M/firmware.bin

      - name: Build with psram support and 16MB Flash firmware
        run: |
          cd ..
          echo "BUILDING MICROLITE_SPIRAM_CAM"
          source ./scripts/build.sh && build_esp32 "MICROLITE_SPIRAM_CAM"
          TARGET=$(pwd)/dependencies/micropython/ports/esp32
          echo "TARGET=$TARGET"
          ./scripts/assemble-unified-image-esp.sh $TARGET "MICROLITE_SPIRAM_CAM"
          ls $TARGET/build-MICROLITE_SPIRAM_CAM
        shell: bash

      - name: Archive ESP32-MICROLITE_SPIRAM_CAM firmware
        uses: actions/upload-artifact@v4
        with:
          name: microlite-esp32-spiram-cam-firmware
          path: /home/runner/work/tensorflow-micropython-examples/dependencies/micropython/ports/esp32/build-MICROLITE_SPIRAM_CAM/firmware.bin
